### ISSUE TITLE
We should rename this repo to `tweeter`

### ISSUE THREAD

**Issue by vaz** [lighthouse-labs/tweeter#22]
We've gotten more consistent about this elsewhere but it's still a thing in the repo name.

**Comment by hora** [comment]
Meaning we also should delete this one: https://github.com/lighthouse-labs/tweeter

Or maybe just overwrite that one with this one – does GitHub allow repo renaming?

**Comment by vaz** [comment]
It does, and it should also make a redirect from the old name.

**Comment by hora** [comment]
Fixed, closing.

**Comment by donburks** [comment]
Resolved this. Renamed old repo to tweeter-old and this one to tweeter.
